"""Tests for wiki writer."""

from pathlib import Path

from gitstyle.models import WikiArticle
from gitstyle.wiki_writer import write_article, write_index, write_meta


def test_write_article(tmp_path: Path):
    article = WikiArticle(
        slug="naming-conventions",
        title="Naming Conventions",
        category="style",
        content="# Naming\n\nUses snake_case for functions.",
        sources=["user/repo"],
        confidence="high",
        related=["code-structure"],
    )
    path = write_article(article, tmp_path)
    assert path.exists()
    text = path.read_text()
    assert "title: \"Naming Conventions\"" in text
    assert "confidence: high" in text
    assert "# Naming" in text


def test_write_article_language(tmp_path: Path):
    article = WikiArticle(
        slug="python",
        title="Python Idioms",
        category="language",
        content="# Python\n\nUses list comprehensions.",
    )
    path = write_article(article, tmp_path)
    assert "languages" in str(path)
    assert path.exists()


def test_write_index(tmp_path: Path):
    articles = [
        WikiArticle(slug="naming-conventions", title="Naming Conventions", category="style", content=""),
        WikiArticle(slug="testing", title="Testing", category="style", content=""),
        WikiArticle(slug="python", title="Python Idioms", category="language", content=""),
    ]
    path = write_index(articles, tmp_path)
    assert path.exists()
    text = path.read_text()
    assert "[[naming-conventions]]" in text
    assert "[[testing]]" in text
    assert "[[languages/python]]" in text


def test_write_meta(tmp_path: Path):
    write_meta(
        config_snapshot={"fetch": {"username": "testuser"}},
        stats={"repos": {"user/repo": 50}, "total_fetched": 100, "total_sampled": 30},
        log_entries=["Generated by gitstyle"],
        output_dir=tmp_path,
    )
    assert (tmp_path / "_meta" / "sources.md").exists()
    assert (tmp_path / "_meta" / "generation-config.md").exists()
    assert (tmp_path / "_meta" / "log.md").exists()

    sources = (tmp_path / "_meta" / "sources.md").read_text()
    assert "user/repo" in sources
    assert "50 commits" in sources
